name: CI

on:
  push:
    branches:
      - main
      - features/*
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  check_composer:
    name: Check composer.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.1'
      - run: composer validate --strict --no-check-lock

  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1' ]
        composer_flags: [ '' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"

      - name: Install dependencies
        run: composer install --ansi --no-progress --prefer-dist --no-interaction ${{ matrix.composer_flags }}

      - name: Run tests
        run: vendor/bin/phpunit -v --colors=always --coverage-clover=coverage.xml
