name: CI

on:
  push:
    branches:
      - main
      - features/*
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
        working-directory: ./
