name: Testing

on:
  push:
    branches:
      - features/**
      - main

    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  php-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - name: Execute tests
        run: vendor/bin/phpunit
